# Generated by Django 4.2.11 on 2024-03-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name or description of the transaction.', max_length=255)),
                ('date', models.DateField(help_text='The date when the transaction occurred.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction.', max_digits=10)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], help_text='The type of the transaction, either Income or Expense.', max_length=7)),
                ('from_account', models.CharField(help_text='The account from which the transaction was made.', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Additional notes about the transaction.', null=True)),
                ('category', models.ForeignKey(help_text='The category this transaction belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('owner', models.ForeignKey(help_text='The user profile that owns this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.userprofile')),
            ],
        ),
    ]
